apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-devenv-k8s
product: kind
registry: devenv-k8s
kindV1Alpha4Cluster:
  nodes:
    - role: control-plane
      image: "kindest/node:v1.28.15@sha256:a7c05c7ae043a0b8c818f5a06188bc2c4098f6cb59ca7d1856df00375d839251"
      extraPortMappings:
        - containerPort: 30080
          hostPort: 80
          protocol: TCP
          listenAddress: "127.0.0.1"

        - containerPort: 30443
          hostPort: 443
          protocol: TCP
          listenAddress: "127.0.0.1"
