apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-devenv-k8s
product: kind
registry: devenv-k8s
kindV1Alpha4Cluster:
  nodes:
    - role: control-plane
      image: "kindest/node:v1.26.15@sha256:c79602a44b4056d7e48dc20f7504350f1e87530fe953428b792def00bc1076dd"
      extraPortMappings:
        - containerPort: 30080
          hostPort: 80
          protocol: TCP
          listenAddress: "127.0.0.1"

        - containerPort: 30443
          hostPort: 443
          protocol: TCP
          listenAddress: "127.0.0.1"
