apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata: # kpt-merge: /svc
  name: svc
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|ApplyReplacements|default|svc'
replacements:
  - source:
      kind: Service
      fieldPath: spec.selector.[app.kubernetes.io/component]
    targets:
      - select:
          kind: Service
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/component]
        options:
          create: true
