apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: app
build:
  tagPolicy:
    gitCommit:
      variant: Tags
  artifacts:
    - image: app
      custom:
        buildCommand: skaffold-builder-buildx
        dependencies:
          dockerfile:
            path: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s/dev/
deploy:
  kubectl: {}
  logs:
    prefix: podAndContainer
---
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: app-deps
manifests:
  kustomize:
    paths:
      - k8s/dev/deps/
deploy:
  kubectl: {}
  logs:
    prefix: podAndContainer
