apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ns/
  - ./helm/
  - ./sa.yaml
  - ./deploy-caddy/
  - ./svc-caddy/
  - ./ing/

namespace: dash

configMapGenerator:
  - name: caddy-config
    files:
      - Caddyfile
