apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ns/
  - ./headlamp.yaml
  - ./sa.yaml
  - ./deploy-caddy/
  - ./svc-caddy/
  - ./ing/

namespace: dash

configMapGenerator:
  - name: caddy-config
    files:
      - Caddyfile

replacements:
  - source:
      kind: Service
      name: headlamp
      fieldPath: metadata.name
    targets:
      - select:
          kind: Deployment
          name: caddy
        fieldPaths:
          - spec.template.spec.containers.[name=default].env.[name=HEADLAMP_SVC_HOSTNAME].value
  - source:
      kind: Service
      name: headlamp
      fieldPath: spec.ports.0.port
    targets:
      - select:
          kind: Deployment
          name: caddy
        fieldPaths:
          - spec.template.spec.containers.[name=default].env.[name=HEADLAMP_SVC_PORT].value
