apiVersion: v1
kind: ServiceAccount
metadata:
  name: dash-user
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dash-user
subjects:
  - kind: ServiceAccount
    name: dash-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: dash-user-token
  annotations:
    kubernetes.io/service-account.name: dash-user
type: kubernetes.io/service-account-token
