# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /example
  # Name will be used as the value for the `app.kubernetes.io/component`
  # selector label and updated automatically by `kpt fn render`.
  # So no need to set those manually.
  name: caddy
  labels:
    app.kubernetes.io/component: caddy
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|example'
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: caddy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: caddy
    spec:
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
      containers:
        - name: default
          image: "caddy"
          env:
            - name: DASH_USER_TOKEN
              valueFrom:
                secretKeyRef:
                  optional: false
                  key: token
                  name: dash-user-token
            - name: HEADLAMP_SVC_HOSTNAME
              value: headlamp
            - name: HEADLAMP_SVC_PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy
