apiVersion: kpt.dev/v1
kind: RenderHelmChart
metadata: # kpt-merge: /example
  name: dashboard
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: kpt.dev|RenderHelmChart|default|example
# See https://catalog.kpt.dev/render-helm-chart/v0.2/
helmCharts:
  - chartArgs:
      repo: https://kubernetes.github.io/dashboard/
      name: kubernetes-dashboard
      version: 7.10.4
    templateOptions:
      apiVersions:
        - 1.26.15
      releaseName: dash
      namespace: dash
      includeCRDs: true
      skipTests: true
      values:
        valuesInline:
          # Chart values go here
          app:
            security:
              csrfKey: fake
            settings:
              global:
                defaultNamespace: _all
